# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'opiCall (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for opiCall (iOS)
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'TwilioVoice', '~> 6.3.0'
  pod 'GoogleMaps', '~> 3.7.0'

end

target 'opiCall (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for opiCall (macOS)

end
